Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(decodeXwithRC_2d.py:1310461): Gdk-CRITICAL **: 10:28:16.884: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
